version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app
    volumes:
      - .:/var/www/symfony
    depends_on:
      - mongo_main

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  mongo_main:
    image: mongo:latest
    container_name: mongo-main
    ports:
      - "27018:27017"
    volumes:
      - mongo_main_data:/data/db

volumes:
  mongo_main_data:
